#!/usr/bin/env python3
"""Append agent memory saves to CLAUDE.md.

Trigger: PostToolUse Write|Edit hook in .claude/settings.json.

Filters tool payloads down to writes targeting an agent memory file
(`*/.claude/projects/<slug>/memory/*.md`, excluding `MEMORY.md`) and
appends the new content as a `---`-fenced entry to CLAUDE.md, inserted
RIGHT BEFORE the `<!-- Generated by Codi -->` marker so the new
content lives in the user-managed zone and survives `codi generate`.

Dedup: SHA256 of `(file_path + content)` recorded in
`.codi/state/claudemd-memory-seen.txt`. A flock guards the file
write to prevent concurrent appends.

The hook is silent on success and non-fatal on errors — failures
print to stderr but never block the agent turn.
"""

from __future__ import annotations

import datetime
import fcntl
import hashlib
import json
import os
import pathlib
import subprocess
import sys


CODI_MARKER = "<!-- Generated by Codi | Do not edit"
SECTION_FENCE = (
    "<!-- AGENT MEMORY CAPTURES — append-only, managed by "
    ".claude/hooks/append-memory-to-claudemd.py -->"
)


def _is_memory_path(path: str) -> bool:
    if "/.claude/projects/" not in path:
        return False
    if "/memory/" not in path:
        return False
    if not path.endswith(".md"):
        return False
    if pathlib.Path(path).name == "MEMORY.md":
        return False
    return True


def _git_author(project_root: pathlib.Path) -> str:
    """Return `name <email>` from git config; falls back to `$USER` then `unknown`.

    Used to attribute each memory capture to the developer who triggered it,
    so multi-dev CLAUDE.md entries are traceable.
    """
    def _cfg(key: str) -> str:
        try:
            out = subprocess.run(
                ["git", "config", "--get", key],
                cwd=project_root,
                capture_output=True,
                text=True,
                timeout=2,
                check=False,
            )
            return out.stdout.strip()
        except (OSError, subprocess.TimeoutExpired):
            return ""

    name = _cfg("user.name") or os.environ.get("USER", "") or "unknown"
    email = _cfg("user.email")
    return f"{name} <{email}>" if email else name


def _read_payload() -> dict:
    raw = sys.stdin.read().strip()
    if not raw:
        return {}
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {}


def _extract_file_path(payload: dict) -> str:
    return (
        payload.get("tool_input", {}).get("file_path")
        or payload.get("file_path")
        or ""
    )


def _insert_entry(claude_md: pathlib.Path, entry: str) -> None:
    text = claude_md.read_text(encoding="utf-8")
    if CODI_MARKER in text:
        idx = text.index(CODI_MARKER)
        top = text[:idx].rstrip()
        bottom = text[idx:]
        if SECTION_FENCE not in top:
            top = f"{top}\n\n{SECTION_FENCE}\n"
        new_text = f"{top.rstrip()}{entry}\n\n{bottom}"
    else:
        if SECTION_FENCE not in text:
            text = f"{text.rstrip()}\n\n{SECTION_FENCE}\n"
        new_text = f"{text.rstrip()}{entry}\n"
    claude_md.write_text(new_text, encoding="utf-8")


def main() -> None:
    payload = _read_payload()
    file_path = _extract_file_path(payload)
    if not file_path or not _is_memory_path(file_path):
        return

    src = pathlib.Path(file_path)
    if not src.is_file():
        return

    project_root = pathlib.Path(
        os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    )
    claude_md = project_root / "CLAUDE.md"
    if not claude_md.is_file():
        return

    state_dir = project_root / ".codi" / "state"
    state_dir.mkdir(parents=True, exist_ok=True)
    state_file = state_dir / "claudemd-memory-seen.txt"
    lock_file = state_dir / ".claudemd-memory.lock"

    content = src.read_text(encoding="utf-8")
    digest = hashlib.sha256(
        f"{file_path}\n{content}".encode("utf-8")
    ).hexdigest()

    if state_file.is_file():
        seen = state_file.read_text(encoding="utf-8").splitlines()
        if digest in seen:
            return

    with open(lock_file, "w", encoding="utf-8") as lf:
        try:
            fcntl.flock(lf.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            return

        ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        slug = src.stem
        author = _git_author(project_root)
        entry = (
            f"\n\n---\n\n"
            f"### {ts} • {slug}\n\n"
            f"- **Author**: {author}\n"
            f"- **Source**: `{file_path}`\n\n"
            f"{content.rstrip()}"
        )

        _insert_entry(claude_md, entry)

        with state_file.open("a", encoding="utf-8") as sf:
            sf.write(digest + "\n")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # noqa: BLE001 — hook must never crash the agent
        sys.stderr.write(f"append-memory-to-claudemd: {exc}\n")
