"""Deterministic canned-JSON :class:`LLMProvider` for tests + CI.

Produces an ``IterationOutput`` shaped to satisfy the parser's
business-rule checks (≤3 personas, ≤5 stories per persona, every
story has ≥1 acceptance criterion, non-empty markdown_rendered,
unique slot keys, etc.).

Crucially, this module has **zero conditional imports** — it works
on the package's base install with no LLM SDK extras. Host CI runs
with ``FEEDBACK_ITER_PROVIDER=fake`` so the Playwright smoke test
exercises the workspace end-to-end without ever calling a real API.

The generated content varies deterministically with the user prompt's
SHA-256 hash so two consecutive calls with the same prompt produce
the same output (idempotency-replay tests rely on this), but
distinct prompts produce distinct documents (so v1 → v2 diffs are
non-empty).
"""

from __future__ import annotations

import asyncio
import hashlib
import json
from collections.abc import AsyncIterator

from .protocol import LLMAttachment, LLMResult, LLMUsage


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _build_canned_output(prompt_digest: str, version_index: int) -> dict[str, object]:
    """Build a valid IterationOutput payload as a plain dict.

    The version_index is inferred from the prompt: a prompt with a
    ``<previous_versions>`` block containing N versions produces
    iteration N+1 with a non-empty diff against version N.
    """
    persona_id = f"p_user_{prompt_digest[:6]}"
    story_id = f"us_{prompt_digest[6:12]}_01"

    markdown = (
        "# Working Document\n\n"
        "## Personas\n\n"
        f"### {persona_id} — Demo User\n"
        "Demo persona generated by the fake provider for tests.\n\n"
        "## User Stories\n\n"
        f"### {story_id} — Demo Story\n"
        "**As a** demo user, **I want** to iterate on feedback, "
        "**so that** the spec converges.\n\n"
        "**Scenario: happy path**\n\n"
        "- Given a feedback row exists\n"
        "- When the user runs an iteration\n"
        "- Then a new version is persisted\n\n"
        "## Spec\n\n"
        "### Goal\n\nDemonstrate the end-to-end flow with canned content.\n\n"
        "## Diagram\n\n"
        "```text\n[user] --(submit)--> [feedback] --(iterate)--> [package]\n```\n"
    )

    diff: list[dict[str, object]] = []
    changes_summary = ""
    if version_index > 1:
        diff = [
            {
                "op": "modify",
                "path": "/spec/sections/0/body_markdown",
                "before": "Demonstrate the end-to-end flow.",
                "after": "Demonstrate the end-to-end flow with canned content.",
                "note": "Refined wording per user request.",
            }
        ]
        changes_summary = "Refined the goal wording to match the user's iteration message."

    return {
        "schema_version": "1",
        "language": "en",
        "personas": [
            {
                "id": persona_id,
                "name": "Demo User",
                "role": "End user",
                "goals": ["Iterate quickly on feedback"],
                "pain_points": ["Implicit assumptions in raw feedback"],
                "context": "Generated by the fake LLM provider for tests.",
            }
        ],
        "user_stories": [
            {
                "id": story_id,
                "persona_id": persona_id,
                "title": "Demo Story",
                "story": {
                    "as_a": "demo user",
                    "i_want": "to iterate on feedback",
                    "so_that": "the spec converges",
                },
                "acceptance_criteria": [
                    {
                        "scenario": "happy path",
                        "given": ["a feedback row exists"],
                        "when": ["the user runs an iteration"],
                        "then": ["a new version is persisted"],
                    }
                ],
            }
        ],
        "spec": {
            "title": "Demo Spec",
            "summary": "Canned spec for the fake LLM provider.",
            "sections": [
                {
                    "id": "sec_goal",
                    "heading": "Goal",
                    "body_markdown": ("Demonstrate the end-to-end flow with canned content."),
                }
            ],
        },
        "diagram": {
            "format": "ascii",
            "source": ("[user] --(submit)--> [feedback] --(iterate)--> [package]"),
            "caption": "End-to-end flow",
        },
        "assumptions": [
            {
                "slot_key": "asm_demo_user_role",
                "kind": "ux",
                "statement": "The user is the feedback submitter.",
                "rationale": (
                    "No explicit actor in the seed feedback; defaulting to the "
                    "submitter is the most common case."
                ),
                "confidence": 0.9,
            }
        ],
        "unresolved_questions": [],
        "diff": diff,
        "changes_summary": changes_summary,
        "archived": [],
        "markdown_rendered": markdown,
    }


def _count_previous_versions(user_prompt: str) -> int:
    """Cheap parse of the tagged user prompt to count prior versions.

    The prompt builder always emits ``<version number="N">`` tags
    inside ``<previous_versions>``; counting them tells us which
    iteration index this call should produce.
    """
    return user_prompt.count('<version number="')


class FakeLLMProvider:
    """Deterministic canned-JSON provider; honours :class:`LLMProvider`."""

    name = "fake"

    @property
    def current_model(self) -> str:
        return "fake"

    async def generate(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        attachments: list[LLMAttachment],
        timeout_seconds: int,
        max_output_tokens: int,
    ) -> LLMResult:
        del attachments, timeout_seconds, max_output_tokens  # canned reply

        digest = _digest(system_prompt + "\n" + user_prompt)
        version_index = _count_previous_versions(user_prompt) + 1
        payload = _build_canned_output(digest, version_index)
        raw = json.dumps(payload, ensure_ascii=False)

        return LLMResult(
            raw_text=raw,
            usage=LLMUsage(
                input_tokens=len(user_prompt) // 4,
                output_tokens=len(raw) // 4,
                latency_ms=10,
            ),
            finish_reason="stop",
            model_id="fake-1",
            model_provider=self.name,
        )

    async def stream(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        attachments: list[LLMAttachment],
        timeout_seconds: int,
        max_output_tokens: int,
    ) -> AsyncIterator[str]:
        result = await self.generate(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            attachments=attachments,
            timeout_seconds=timeout_seconds,
            max_output_tokens=max_output_tokens,
        )
        # Chunk into ~64-char pieces with a tiny await between them so
        # the event loop yields and the SSE consumer sees real streaming
        # behaviour rather than a single big chunk.
        chunk_size = 64
        for i in range(0, len(result.raw_text), chunk_size):
            yield result.raw_text[i : i + chunk_size]
            await asyncio.sleep(0)

    def estimate_cost_usd(self, usage: LLMUsage) -> float | None:
        del usage
        return 0.0
